#index:
#    path: /
#    defaults: { _controller: 'App\Controller\DefaultController::index' }

#route the "app_lucky_number"

app_lucky_number:
    path: /lucky/number
    controller: App\Controller\LuckyController::number
